v0.1-alpha-81

diff --git a/uconf/bin/do b/uconf/bin/do
--- a/uconf/bin/do
+++ b/uconf/bin/do
@@ -4,7 +4,7 @@
 #
 # Copyright 2014-2015 Pedro A. Hortas (pah@ucodev.org)
 #
-# Date: 22/03/2015
+# Date: 23/03/2015
 #
 # URL: http://www.ucodev.org
 #
@@ -69,6 +69,17 @@ if [ -e ./uconf/params/`cat .osname 2> /dev/null`/do ]; then
 			exit 1
 		fi
 	done < ./uconf/params/`cat .osname`/do
+fi
+
+if [ -e ./uconf/params/user/do ]; then
+	while read cmd; do
+		/bin/sh -c "${cmd}"
+
+		if [ $? -ne 0 ]; then
+			echo "Failed to execute: ${cmd}"
+			exit 1
+		fi
+	done < ./uconf/params/user/do
 fi
 
 touch .done
diff --git a/uconf/bin/install b/uconf/bin/install
--- a/uconf/bin/install
+++ b/uconf/bin/install
@@ -4,7 +4,7 @@
 #
 # Copyright 2014-2015 Pedro A. Hortas (pah@ucodev.org)
 #
-# Date: 16/03/2015
+# Date: 23/03/2015
 #
 # URL: http://www.ucodev.org
 #
@@ -55,6 +55,17 @@ if [ -e ./uconf/params/`cat .osname 2> /dev/null`/install ]; then
 			exit 1
 		fi
 	done < ./uconf/params/`cat .osname`/install
+fi
+
+if [ -e ./uconf/params/user/install ]; then
+	while read cmd; do
+		/bin/sh -c "${cmd}"
+
+		if [ $? -ne 0 ]; then
+			echo "Failed to execute: ${cmd}"
+			exit 1
+		fi
+	done < ./uconf/params/user/install
 fi
 
 echo "Installation complete."
diff --git a/uconf/bin/undo b/uconf/bin/undo
--- a/uconf/bin/undo
+++ b/uconf/bin/undo
@@ -4,7 +4,7 @@
 #
 # Copyright 2014-2015 Pedro A. Hortas (pah@ucodev.org)
 #
-# Date: 22/03/2015
+# Date: 23/03/2015
 #
 # URL: http://www.ucodev.org
 #
@@ -53,6 +53,19 @@ if [ -e ./uconf/params/`cat .osname 2> /dev/null`/undo ]; then
 		fi
 	done < ./uconf/params/`cat .osname`/undo
 fi
+
+if [ -e ./uconf/params/user/undo ]; then
+	while read cmd; do
+		/bin/sh -c "${cmd}"
+
+		if [ $? -ne 0 ]; then
+			echo "Failed to execute: ${cmd}"
+			exit 1
+		fi
+	done < ./uconf/params/user/undo
+fi
+
+rm -rf ./uconf/params/user
 
 rm -rf build
 rm -f .target
