v0.1-alpha-28

diff --git a/uconf/bin/undo b/uconf/bin/undo
--- a/uconf/bin/undo
+++ b/uconf/bin/undo
@@ -5,7 +5,27 @@ if [ `id -u` -ne 0 ]; then
 	exit 1
 fi
 
-make clean
+if [ -e ./uconf/params/default/undo ]; then
+	while read cmd; do
+		/bin/sh -c "${cmd}"
+
+		if [ $? -ne 0 ]; then
+			echo "Failed to execute: ${cmd}"
+			exit 1
+		fi
+	done < ./uconf/params/default/undo
+fi
+
+if [ -e ./uconf/params/`cat .osname 2> /dev/null`/undo ]; then
+	while read cmd; do
+		/bin/sh -c "${cmd}"
+
+		if [ $? -ne 0 ]; then
+			echo "Failed to execute: ${cmd}"
+			exit 1
+		fi
+	done < ./uconf/params/`cat .osname`/undo
+fi
 
 rm -rf build
 rm -f .target
